# Site settings
title: Ads Boomerang
description: "The Official Blog of Ads Boomerang"

# For example, my configuration is this:
# url: https://blog.adsboomerang.com
enforce_ssl: blog.adsboomerang.com

author:
  name: "Ads Boomerang"
  email: "hello@adsboomerang.com"
  url: "https://adsboomerang.com"

# Build settings
baseurl: https:///blog.adsboomerang.com # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - github-pages

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
